# Generated by Django 5.2.5 on 2025-11-09 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0002_product_discount_end_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-discount_percent', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['-discount_percent', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='product',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='flash_sales', to='category.category'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashsale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='flash_sales', to='store.product'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='title',
            field=models.CharField(default='Flash Sale', max_length=200),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='category.category'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='discount_percent',
            field=models.PositiveIntegerField(help_text='Discount percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='store.product'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='discount_percent',
            field=models.PositiveIntegerField(help_text='Discount percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Product-specific discount (0-100)'),
        ),
    ]
