# Generated by Django 5.2.5 on 2025-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bannerslider_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslider',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
