# Generated by Django 5.2.5 on 2025-11-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_description'),
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='products',
        ),
        migrations.CreateModel(
            name='FlashSaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Discount percentage for this category in the flash sale (0-100)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='category.category')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_categories', to='store.flashsale')),
            ],
            options={
                'ordering': ['-discount_percent'],
                'unique_together': {('flash_sale', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Discount percentage for this product in the flash sale (0-100)')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_products', to='store.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='store.product')),
            ],
            options={
                'ordering': ['-discount_percent'],
                'unique_together': {('flash_sale', 'product')},
            },
        ),
    ]
