# Generated by Django 5.2.5 on 2025-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productview_store_produ_session_71eb85_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_bn',
            field=models.TextField(blank=True, default='This product is designed to provide excellent quality and reliable performance for everyday use. Made with durable materials and crafted with attention to detail, it offers comfort, convenience, and lasting value.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='This product is designed to provide excellent quality and reliable performance for everyday use. Made with durable materials and crafted with attention to detail, it offers comfort, convenience, and lasting value.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_bn',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
