# Generated by Django 5.2.5 on 2026-01-21 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_cat_img'),
        ('store', '0017_remove_product_images_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerslider',
            options={'ordering': ['position']},
        ),
        migrations.AddIndex(
            model_name='bannerslider',
            index=models.Index(fields=['is_active', 'position'], name='store_banne_is_acti_48e043_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-discount_percent', '-start_date'], name='store_campa_discoun_9fd199_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['start_time', 'end_time', 'is_active'], name='store_flash_start_t_db69ef_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsalecategory',
            index=models.Index(fields=['flash_sale', 'category'], name='store_flash_flash_s_06d522_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsalecategory',
            index=models.Index(fields=['category', '-discount_percent'], name='store_flash_categor_54a62b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['flash_sale', 'product'], name='store_flash_flash_s_e072fa_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['product', '-discount_percent'], name='store_flash_product_596595_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', '-viewed_at'], name='store_produ_product_ae4ff5_idx'),
        ),
    ]
