# Generated by Django 5.2.5 on 2026-01-18 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cat_img'),
        ),
    ]
